# List of topics to be processed by the knowledge base generator.
# These topics will guide the content generation process.
topics:
  - Knowledge Management
  # - Entrepreneurship
  # - Decisions
  # - Optimization
  # - Large Language Models (LLMs)
  # - Prompt Engineering
  # - Artificial Intelligence (AI)
  # - Machine Learning (ML)
  # - Data
  # - Data Science
  # - Data Analytics
  # - Data Engineering
  # - Mathematics
  # - Statistics
  # - Computer Science
  # - Software Engineering
  # - Knowledge Graphs
  # - Semantic Web
  # - Ontologies

# Agent configuration section
agent:
  model: 'gpt-4o'
  system_prompt: 'You are a knowledge base generator for post-doctoral researchers...'
  description_max_words: 1000
  max_iterations: 5
  retry_attempts: 3

# Tools configuration section
tools:
  serper_enabled: true
  tavily_enabled: true
  reddit_enabled: true
  searxng_enabled: true
  semantic_scholar_enabled: true
  wikidata_enabled: true
  wikipedia_enabled: true
  max_search_results: 10
  max_depth: 1

# Output configuration section
output:
  working_directory: './kb_output'
  file_format: 'markdown'
  include_metadata: true

# Logging configuration section
logging:
  level: 'INFO'
  format: '{time} - {name} - {level} - {message}'
  log_to_file: true
  log_file_path: './logs/agent.log'
  log_to_console: true
  log_structured_file: true

# WebSocket API configuration section
websocket_api:
  host: '0.0.0.0'
  port: 8000
  log_level: 'info'
  allowed_origins:
    - '*'
