[tool.poetry]
name = "my_agent"
version = "0.1.0"
description = "Example LangGraph project for deployment to LangGraph Cloud"
authors = [
    "langchain-ai"
]
packages = [
    { include = "my_agent" },
]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.13"
langgraph = "^0.2.0"
langchain_anthropic = "^0.1.0"
langchain_core = "^0.2.0"
langchain_openai = "^0.1.0"
tavily-python = "^0.3.0"
langchain_community = "^0.2.0"
langfuse = "^0.1.0"
langsmith = "^0.1.0"
loguru = "^0.5.3"
rich = "^10.9.0"
tqdm = "^4.62.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
